### ISSUE TITLE
Several sounds play the crystal breaking sound when they shouldn't

### ISSUE THREAD

**Issue by Rob1200489** [Rob1200489/AzzyBattlesTheDarkness#15]
The following interactions cause a crystal breaking sound instead of the sounds that they are supposed to play:
- Azzy igniting vines with fireball
- Azzy being damaged by vines

**Comment by KieranMackintosh** [comment]
I was looking at some SFX last night and Fin was getting them ready in FMOD. At the time, he said he'll get them in the engine tomorrow.

Once they're in we'll identify where else SFX are needed and repeat the process.

**Comment by KieranMackintosh** [comment]
More sounds have been added, but I'm unable to make FMOD talk to Unreal via Perforce on my machine. However, Fin is able to have both talking to each other on his machine.
