### ISSUE TITLE
Troublesome Collision

### ISSUE THREAD

**Issue by KieranMackintosh** [Rob1200489/AzzyBattlesTheDarkness#6]
![image](https://user-images.githubusercontent.com/70520551/92122224-185ff880-edf3-11ea-943b-fd64fe10338e.png)
I fell into this area and it zoomed the camera right in on the character, clipping through him. When I got out, the camera was offset so that camera was much more on the right side of the screen. Interestingly, going back into this re-aligned the camera after a couple of tries. 

Don't know whether to remove the rock on the right (in the picture) or to add a collision volume.

**Comment by Rob1200489** [comment]
Fixed
