### ISSUE TITLE
Ground near the first grapple ring has weird collision

### ISSUE THREAD

**Issue by Rob1200489** [Rob1200489/AzzyBattlesTheDarkness#9]
The collision of the ground near the first grapple ring is wrong (see image)
![Bug2](https://user-images.githubusercontent.com/50617758/92157629-9982b400-ee22-11ea-8c75-be131ffc4f69.png)

**Comment by KieranMackintosh** [comment]
A solution has been implemented, please test!

**Comment by Rob1200489** [comment]
Tested again, bug has been fixed
